package raycluster

// Annotation that marks a RayCluster as migrated to secure trusted network (RHOAI 3.x).
const SecureNetworkAnnotation = "odh.ray.io/secure-trusted-network"

// Field manager identifier for server-side apply (kept for compatibility with codeflare-sdk).
const FieldManager = "codeflare-sdk"

// TLS-related environment variable names to remove or detect.
var TLSEnvVars = map[string]struct{}{
	"RAY_USE_TLS":        {},
	"RAY_TLS_SERVER_CERT": {},
	"RAY_TLS_SERVER_KEY":  {},
	"RAY_TLS_CA_CERT":    {},
}

// Volume names to remove (TLS/OAuth).
var VolumesToRemove = map[string]struct{}{
	"ca-vol":             {},
	"proxy-tls-secret":   {},
	"server-cert":       {},
}

// Volume mount names to remove from containers.
var VolumeMountsToRemove = map[string]struct{}{
	"ca-vol":     {},
	"server-cert": {},
}

// Sidecar container names to remove (e.g. oauth-proxy).
var ContainersToRemove = map[string]struct{}{
	"oauth-proxy": {},
}

// CodeFlare initContainer names to remove (cert generation).
var CodeFlareInitContainers = map[string]struct{}{
	"create-cert": {},
}

// Kueue annotation keys to strip from backup/restore. Kueue sets these on the
// Workload and pod templates; old values from a deleted cluster cause admission
// conflicts when applying a backup (value1=old workload name, value2=new).
var KueueAnnotationsToStrip = map[string]struct{}{
	"kueue.x-k8s.io/workload": {},
	"kueue.x-k8s.io/podset":   {},
}

// Autogenerated metadata keys to strip from backup/replace.
var AutogeneratedFields = map[string]struct{}{
	"creationTimestamp": {},
	"resourceVersion":   {},
	"uid":               {},
	"selfLink":          {},
	"managedFields":     {},
	"finalizers":        {},
	"generation":        {},
	"status":            {},
	"workload.codeflare.dev/user":   {},
	"workload.codeflare.dev/userid": {},
	"podSetInfos":       {},
}

// Default backup directory when not specified.
const DefaultBackupDir = "./raycluster-backups"

// Subdirectory names for RHOAI 2.x and 3.x backups.
const (
	BackupSubdirRHOAI2x = "rhoai-2.x"
	BackupSubdirRHOAI3x = "rhoai-3.x"
)
